In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from source.TrainDataGeneration import append_ORD_TM,append_ORD_VOL,append_TM_GP,GetGroupDataFrame,append_STEP5

In [2]:
idx=128*50

In [3]:
RandomXData=np.floor(np.random.random((39*idx,2))*3)


In [4]:
RandomXData

array([[1., 0.],
       [0., 0.],
       [0., 2.],
       ...,
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [5]:
RandomXData[1:,0]

array([0., 0., 2., ..., 1., 2., 1.])

In [6]:
#Future Data
RandomYData=np.floor(np.random.random(39*idx)*3)
RandomYData=RandomXData[1:,0].squeeze()
RandomYData = np.append(RandomYData,2)

In [7]:
#Current Data
# RandomYData[:]=RandomXData[:,0].squeeze()

In [8]:
RandomYData

array([0., 0., 2., ..., 2., 1., 2.])

In [9]:
ylabel=pd.Series(RandomYData)

In [10]:
SaveDirPath='/Data/Min/TransLOB/TrainData/'
DataSubfix="RandomTest"
TrainDataname='Train_ORD'+'_'+DataSubfix
TrainLabelDataname='Train_ORD_Label__'+DataSubfix
np.save(SaveDirPath+TrainDataname,RandomXData)
np.save(SaveDirPath+TrainLabelDataname,ylabel)
print("path:",SaveDirPath+TrainDataname)
print("path:",SaveDirPath+TrainLabelDataname)


path: /Data/Min/TransLOB/TrainData/Train_ORD_RandomTest
path: /Data/Min/TransLOB/TrainData/Train_ORD_Label__RandomTest
